
export type Language = 'en' | 'es' | 'fr';

export const LOCALIZATION = {
  en: {
    start: 'START',
    score: 'SCORE',
    settings: 'SETTINGS',
    sector: 'SECTOR',
    time: 'TIME',
    alignment: 'ALIGNMENT RESONANCE',
    output: 'CURRENT OUTPUT',
    subsystems: 'SUB-SYSTEMS',
    abortMission: 'ABORT MISSION',
    hallOfFame: 'HALL OF FAME',
    closeFame: 'CLOSE FAME',
    missionTerminated: 'MISSION TERMINATED',
    reboot: 'REBOOT SYSTEM',
    victory: 'VICTORY',
    abandonMission: 'ABANDON MISSION?',
    abandonDesc: 'Neural link will be severed. All sector telemetry will be lost to the void.',
    yes: 'YES',
    no: 'NO',
    paused: 'PAUSED',
    protocol: 'CELESTIAL ALIGNMENT PROTOCOL',
    best: 'PERSONAL BEST',
    highest: 'HIGHEST SECTOR',
    waiting: 'Waiting for telemetry...',
    archive: 'ARCHIVE LOGS',
    sound: 'SOUND',
    music: 'MUSIC',
    language: 'LANGUAGE',
    exit: 'EXIT',
    profile: 'PLAYER PROFILE',
    rank: 'SPACE RANK',
    xp: 'EXPERIENCE',
    stats: 'TELEMETRY STATS',
    matches: 'TOTAL MATCHES',
    wins: 'GAMES WON',
    stars: 'STARS COLLECTED',
    allTimeHigh: 'ALL-TIME HIGH',
    changeAvatar: 'CHANGE AVATAR',
    editName: 'EDIT NAME',
    cadet: 'CADET',
    pilot: 'PILOT',
    commander: 'COMMANDER',
    admiral: 'ADMIRAL',
    legend: 'COSMIC LEGEND'
  },
  es: {
    start: 'INICIAR',
    score: 'PUNTUACIÓN',
    settings: 'AJUSTES',
    sector: 'SECTOR',
    time: 'TIEMPO',
    alignment: 'RESONANCIA DE ALINEACIÓN',
    output: 'PRODUCCIÓN ACTUAL',
    subsystems: 'SUB-SISTEMAS',
    abortMission: 'ABORTAR MISIÓN',
    hallOfFame: 'SALÓN DE LA FAMA',
    closeFame: 'CERRAR FAMA',
    missionTerminated: 'MISIÓN TERMINADA',
    reboot: 'REINICIAR SISTEMA',
    victory: 'VICTORIA',
    abandonMission: '¿ABANDONAR MISIÓN?',
    abandonDesc: 'El enlace neuronal se cortará. Toda la telemetría se perderá en el vacío.',
    yes: 'SÍ',
    no: 'NO',
    paused: 'PAUSADO',
    protocol: 'PROTOCOLO DE ALINEACIÓN CELESTIAL',
    best: 'RÉCORD PERSONAL',
    highest: 'SECTOR MÁS ALTO',
    waiting: 'Esperando telemetría...',
    archive: 'REGISTROS DE ARCHIVO',
    sound: 'SONIDO',
    music: 'MÚSICA',
    language: 'IDIOMA',
    exit: 'SALIR',
    profile: 'PERFIL DE JUGADOR',
    rank: 'RANGO ESPACIAL',
    xp: 'EXPERIENCIA',
    stats: 'ESTADÍSTICAS',
    matches: 'TOTAL DE COMBINACIONES',
    wins: 'PARTIDAS GANADAS',
    stars: 'ESTRELLAS RECOLECTADAS',
    allTimeHigh: 'RÉCORD HISTÓRICO',
    changeAvatar: 'CAMBIAR AVATAR',
    editName: 'EDITAR NOMBRE',
    cadet: 'CADETE',
    pilot: 'PILOTO',
    commander: 'COMANDANTE',
    admiral: 'ALMIRANTE',
    legend: 'LEYENDA CÓSMICA'
  },
  fr: {
    start: 'COMMENCER',
    score: 'SCORE',
    settings: 'RÉGLAGES',
    sector: 'SECTEUR',
    time: 'TEMPS',
    alignment: 'RÉSONANCE D\'ALIGNEMENT',
    output: 'SORTIE ACTUELLE',
    subsystems: 'SOUS-SYSTÈMES',
    abortMission: 'ABANDONNER LA MISSION',
    hallOfFame: 'PANTHEON',
    closeFame: 'FERMER PANTHEON',
    missionTerminated: 'MISSION TERMINÉE',
    reboot: 'REDÉMARRER LE SYSTÈME',
    victory: 'VICTOIRE',
    abandonMission: 'ABANDONNER LA MISSION ?',
    abandonDesc: 'Le lien neural sera rompu. Toute la télémétrie du secteur sera perdue dans le vide.',
    yes: 'OUI',
    no: 'NON',
    paused: 'PAUSE',
    protocol: 'PROTOCOLE D\'ALIGNEMENT CÉLESTE',
    best: 'RECORD PERSONNEL',
    highest: 'SECTEUR MAXIMUM',
    waiting: 'En attente de télémétrie...',
    archive: 'LOGS D\'ARCHIVE',
    sound: 'SON',
    music: 'MUSIQUE',
    language: 'LANGUE',
    exit: 'QUITTER',
    profile: 'PROFIL DU JOUEUR',
    rank: 'RANG SPATIAL',
    xp: 'EXPÉRIENCE',
    stats: 'STATISTIQUES',
    matches: 'TOTAL DES MATCHS',
    wins: 'PARTIES GAGNÉES',
    stars: 'ÉTOILES COLLECTÉES',
    allTimeHigh: 'MEILLEUR SCORE',
    changeAvatar: 'CHANGER L\'AVATAR',
    editName: 'MODIFIER LE NOM',
    cadet: 'CADET',
    pilot: 'PILOTE',
    commander: 'COMMANDANT',
    admiral: 'AMIRAL',
    legend: 'LÉGENDE COSMIQUE'
  }
};
