
export type Language = 'en' | 'es' | 'fr';

export const LOCALIZATION = {
  en: {
    start: 'START',
    score: 'SCORE',
    settings: 'SETTINGS',
    sector: 'SECTOR',
    time: 'TIME',
    alignment: 'ALIGNMENT',
    output: 'OUTPUT',
    subsystems: 'SUBSYSTEMS',
    abortMission: 'ABORT',
    hallOfFame: 'HALL OF FAME',
    closeFame: 'CLOSE',
    missionTerminated: 'MISSION TERMINATED',
    reboot: 'REBOOT',
    victory: 'MISSION ACCOMPLISHED',
    abandonMission: 'ABANDON?',
    abandonDesc: 'Neural link will be severed. Telemetry will be lost.',
    yes: 'YES',
    no: 'NO',
    paused: 'PAUSED',
    protocol: 'CELESTIAL ALIGNMENT PROTOCOL',
    best: 'BEST',
    highest: 'HIGHEST',
    waiting: 'Waiting...',
    archive: 'ARCHIVE',
    sound: 'SOUND',
    language: 'LANGUAGE',
    exit: 'EXIT',
    profile: 'PROFILE',
    rank: 'RANK',
    xp: 'XP',
    stats: 'STATS',
    matches: 'MATCHES',
    wins: 'WINS',
    stars: 'STARS',
    allTimeHigh: 'HIGH SCORE',
    changeAvatar: 'AVATAR',
    editName: 'NAME',
    cadet: 'CADET',
    pilot: 'PILOT',
    commander: 'COMMANDER',
    admiral: 'ADMIRAL',
    legend: 'LEGEND',
    batterySaver: 'BATTERY SAVER',
    on: 'ON',
    off: 'OFF',
    coins: 'COINS'
  },
  es: {
    start: 'INICIAR',
    score: 'PUNTOS',
    settings: 'AJUSTES',
    sector: 'SECTOR',
    time: 'TIEMPO',
    alignment: 'ALINEACIÓN',
    output: 'PRODUCCIÓN',
    subsystems: 'SISTEMAS',
    abortMission: 'ABORTAR',
    hallOfFame: 'FAMA',
    closeFame: 'CERRAR',
    missionTerminated: 'TERMINADA',
    reboot: 'REINICIAR',
    victory: 'MISIÓN CUMPLIDA',
    abandonMission: '¿ABANDONAR?',
    abandonDesc: 'Enlace neuronal roto. Telemetría perdida.',
    yes: 'SÍ',
    no: 'NO',
    paused: 'PAUSADO',
    protocol: 'PROTOCOLO DE ALINEACIÓN',
    best: 'RÉCORD',
    highest: 'MÁXIMO',
    waiting: 'Esperando...',
    archive: 'ARCHIVO',
    sound: 'SONIDO',
    language: 'IDIOMA',
    exit: 'SALIR',
    profile: 'PERFIL',
    rank: 'RANGO',
    xp: 'XP',
    stats: 'ESTADÍSTICAS',
    matches: 'COMBOS',
    wins: 'GANADAS',
    stars: 'ESTRELLAS',
    allTimeHigh: 'MÁXIMO',
    changeAvatar: 'AVATAR',
    editName: 'NOMBRE',
    cadet: 'CADETE',
    pilot: 'PILOTO',
    commander: 'COMANDANTE',
    admiral: 'ALMIRANTE',
    legend: 'LEYENDA',
    batterySaver: 'AHORRO BATERÍA',
    on: 'SÍ',
    off: 'NO',
    coins: 'MONEDAS'
  },
  fr: {
    start: 'COMMENCER',
    score: 'SCORE',
    settings: 'RÉGLAGES',
    sector: 'SECTEUR',
    time: 'TEMPS',
    alignment: 'ALIGNEMENT',
    output: 'SORTIE',
    subsystems: 'SYSTÈMES',
    abortMission: 'ABANDON',
    hallOfFame: 'PANTHEON',
    closeFame: 'FERMER',
    missionTerminated: 'TERMINÉE',
    reboot: 'REDÉMARRER',
    victory: 'MISSION ACCOMPLIE',
    abandonMission: 'ABANDONNER ?',
    abandonDesc: 'Lien neural rompu. Télémétrie perdue.',
    yes: 'OUI',
    no: 'NON',
    paused: 'PAUSE',
    protocol: 'PROTOCOLE D\'ALIGNEMENT',
    best: 'RECORD',
    highest: 'MAXIMUM',
    waiting: 'Attente...',
    archive: 'ARCHIVE',
    sound: 'SON',
    language: 'LANGUE',
    exit: 'QUITTER',
    profile: 'PROFIL',
    rank: 'RANG',
    xp: 'XP',
    stats: 'STATS',
    matches: 'MATCHS',
    wins: 'VICTOIRES',
    stars: 'ÉTOILES',
    allTimeHigh: 'RECORD',
    changeAvatar: 'AVATAR',
    editName: 'NOM',
    cadet: 'CADET',
    pilot: 'PILOTE',
    commander: 'COMMANDANT',
    admiral: 'AMIRAL',
    legend: 'LÉGENDE',
    batterySaver: 'ÉCONOMIE BATT.',
    on: 'OUI',
    off: 'NON',
    coins: 'PIÈCES'
  }
};
